# Generated by Django 5.0.6 on 2024-05-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='schema',
            field=models.JSONField(default=dict),
        ),
    ]
