# Generated by Django 5.0.6 on 2024-05-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0005_alter_user_password_alter_user_repassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='lastname',
        ),
    ]
