# Generated by Django 5.0.6 on 2024-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0008_rename_fullname_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='Name', max_length=32),
        ),
    ]
