# Generated by Django 5.0.6 on 2024-05-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='member',
        ),
    ]
