# Generated by Django 5.0.6 on 2024-05-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0012_rename_user_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='User',
        ),
    ]
