# Generated by Django 5.0.6 on 2024-05-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0003_user'),
    ]

    operations = [
    ]
