# Generated by Django 5.0.6 on 2024-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0004_auto_20240512_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='rePassword',
            field=models.CharField(max_length=128),
        ),
    ]
