# Generated by Django 5.0.6 on 2024-05-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0006_rename_fname_user_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
    ]
