# Generated by Django 5.0.6 on 2024-05-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0014_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
