# Generated by Django 5.0.6 on 2024-07-01 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0016_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='inserted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
