# Generated by Django 5.0.6 on 2024-07-01 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0017_item_date_added_alter_product_inserted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inserted_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
