# Generated by Django 5.0.6 on 2024-07-01 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0020_remove_product_inserted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inserted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
