# Generated by Django 5.0.6 on 2024-07-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0022_remove_item_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
