# Generated by Django 5.0.6 on 2024-07-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0023_remove_item_brand_remove_item_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
