# Generated by Django 5.0.6 on 2024-07-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0024_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='formschema',
            new_name='data',
        ),
    ]
